(define (improve guess x) (average guess (/ x guess)))
(define (average x y) (/ (+ x y) 2))
(define (good-enough? guess prev-guess) (< (abs (- guess prev-guess)) 0.001))
(define (sqrt-iter prev-guess guess x) (if (good-enough? guess prev-guess) guess (sqrt-iter guess (improve guess x) x)))
(define (sqrt x) (sqrt-iter 0 1.0 x))
